# Generated by Django 4.2.1 on 2023-08-16 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_remove_comment_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='messsage',
            new_name='message',
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog_app.blog'),
        ),
    ]
